### ISSUE TITLE
Align versioning of dagger-for-github with dagger engine?

### ISSUE THREAD

**Issue by shykes** [dagger/dagger-for-github#24]
It seems that dagger-for-github has its own versioning: `v1`, `v2`, etc. I understand how this makes sense (it is its own software, makes sense to have its own versioning schema). But from the point of view of a Dagger user, I find it confusing because I only care about version of Dagger. How do I choose the right version of dagger-for-github? I might have to look up a version mapping...

it would be great if we could change the versioning of dagger-for-github so that it aligns with the versioning of dagger (ie. version 0.2 -> 0.2). Thoughts?

**Comment by shykes** [comment]
Copying @gerhard so he can track which tag to use in getting started.

**Comment by gerhard** [comment]
We (+ @crazy-max @aluzzardi) have decided to keep versioning as is because there will be changes that we will need to make in the action that are unrelated to Dagger (e.g. upgrade node version, add new config parameters, etc.).

The simplest thing was to link `v1` in the action to Dagger 0.1 (pre-Europa) https://github.com/dagger/dagger-for-github/pull/28 and create `v2` which defaults to Dagger 0.2 (Europa) https://github.com/dagger/dagger-for-github/pull/30

This can be closed for now, but we should re-open if we think this is still relevant.

**Comment by shykes** [comment]
I agree, this makes sense, especially since you can configure the version of `dagger` to use in the action.
